In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
import tensorflow as tf
from tensorflow import keras

In [2]:
data={'Dear':[1,1,0,1],'Dinner':[2,0,3,0],'Money':[1,4,0,2],'Status':[0,1,0,1]}
df=pd.DataFrame(data,index=['Mail 1','Mail 2','Mail 3','Mail 4'])

In [3]:
df

Dear  Dinner  Money  Status
Mail 1     1       2      1       0
Mail 2     1       0      4       1
Mail 3     0       3      0       0
Mail 4     1       0      2       1

In [4]:
x=df.drop('Status',axis=1)
y=df.Status

In [5]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=5)

In [6]:
len(xtrain.columns)

3

In [7]:
model=keras.Sequential([
    keras.layers.Dense(3,input_shape=(3,),activation='relu'),
    keras.layers.Dense(1,activation='sigmoid')
])

In [8]:
opt = tf.keras.optimizers.Adam()
model.compile(loss='binary_crossentropy', optimizer=opt,metrics=['accuracy'])

In [9]:
model.fit(xtrain,ytrain,epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 321ms/step - loss: 0.4307 - accuracy: 1.0000
Epoch 2/10
1/1 [==============================] - 0s 2ms/step - loss: 0.4275 - accuracy: 1.0000
Epoch 3/10
1/1 [==============================] - 0s 3ms/step - loss: 0.4243 - accuracy: 1.0000
Epoch 4/10
1/1 [==============================] - 0s 2ms/step - loss: 0.4211 - accuracy: 1.0000
Epoch 5/10
1/1 [==============================] - 0s 2ms/step - loss: 0.4179 - accuracy: 1.0000
Epoch 6/10
1/1 [==============================] - 0s 2ms/step - loss: 0.4148 - accuracy: 1.0000
Epoch 7/10
1/1 [==============================] - 0s 2ms/step - loss: 0.4118 - accuracy: 1.0000
Epoch 8/10
1/1 [==============================] - 0s 2ms/step - loss: 0.4087 - accuracy: 1.0000
Epoch 9/10
1/1 [==============================] - 0s 2ms/step - loss: 0.4057 - accuracy: 1.0000
Epoch 10/10
1/1 [==============================] - 0s 2ms/step - loss: 0.4028 - accuracy: 1.0000


In [10]:
model.evaluate(xtest,ytest)

1/1 [==============================] - 0s 78ms/step - loss: 0.4169 - accuracy: 1.0000


[0.4168618321418762, 1.0]

In [13]:
model.get_weights()

[array([[ 0.5155148 , -0.8943673 ,  0.95388764],
        [ 0.37715232,  0.31942406, -0.4197197 ],
        [ 0.40728524,  0.90081894,  0.36639285]], dtype=float32),
 array([-0.00990487,  0.00992176,  0.0099701 ], dtype=float32),
 array([[-0.7499182 ],
        [ 0.33221376],
        [ 0.74028546]], dtype=float32),
 array([0.00991014], dtype=float32)]

In [17]:
print(model.predict([[2,1,0]]))

1/1 [==============================] - 0s 21ms/step
[[0.5175636]]
